name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true # Use Node.js 12 for this job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to S3
        run: |
          aws s3 sync ./path/to/static/files s3://crisandeirrell
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
